name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        csvinput: |
          First Name, Last Name, Address, Town, State, Zip
          John,Doe,120 jefferson st.,Riverside, NJ, 08075
          Jack,McGinnis,220 hobo Av.,Phila, PA,09119
